# Generated by Django 4.1.7 on 2023-04-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heart', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='gyro',
            fields=[
                ('index', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gyro_x', models.FloatField(max_length=10)),
                ('gyro_y', models.FloatField(max_length=10)),
                ('gyro_z', models.FloatField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iot_receiver.data')),
            ],
        ),
        migrations.CreateModel(
            name='acc',
            fields=[
                ('index', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acc_x', models.FloatField(max_length=10)),
                ('acc_y', models.FloatField(max_length=10)),
                ('acc_z', models.FloatField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iot_receiver.data')),
            ],
        ),
    ]
