# Generated by Django 4.1.7 on 2023-04-19 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 19, 19, 26, 8, 102562, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
